### PR TITLE
Major refactor

### LINKED ISSUE #6: Improve parser errors on incorrect type
Currently, when e.g. trying to parse a `bool` but getting a number, the error is:
```
expected [Name], got Some(Number)
```
Should at least include the type currently being parsed, e.g.
```
error parsing Bool: expected [Name], got Some(Number)
```

### LINKED ISSUE #17: "Empty set" ambiguity
An "empty set" value `{}` has two possible interpretations: a `flags` value with zero flags set or a `record` value with all field values set to `none` (because "Record entries with the option-typed value none may be omitted").

The WAVE parser in this repo avoids this ambiguity because it is type-driven, but any alternative implementation that wanted to parse to an AST would need to address it.

I see two obvious options:

- Disallow `{}` for records. A `record` with all fields values set to `none` would need to specify at least one of those fields explicitly, e.g. `{optional-field: none}`
- Give `{}` its own formal rule (e.g. `empty-set := '{' '}'`) and accept the AST ambiguity. AST ambiguity is already present for other Component Model value representations such as various number types and `bool`s (vs variant case labels).

### LINKED ISSUE #18: Treat `inf`, `nan`, `true`, `false` as keywords
Currently there's ambiguity with `inf`/`nan` between floating-point or variant-case. We could just accept this as a quirk that we resolve using the type, however an advantage of resolving it in the grammar is that type-unaware syntax highlighters would be able to highlight `inf`, `nan`, `true`, and `false` differently from identifiers.

Consequently, I propose we interpret `inf`, `nan`, `true`, and `false` as keywords, and require a `%` when they're intended as identifiers.

Should we do the same for `some`/`none`/`ok`/`err`? This feels less important, because `option`/`result` despecialize to `variant` anyway. However, they are somewhat special, with special syntax in a few places. I'd be ok going either way on these, but have a slight preference for treating `some`/`none`/`ok`/`err` as keywords.

Thoughts?

### PR DESCRIPTION
**Pull request by lann**
This change ended up changing a large percentage of the codebase. Some highlights:

- Reimplemented the lexer using the `logos` crate
- Resolved ambiguity between variant labels and keywords. Builtin keywords must now be '%'-prefixed in top-level value position.
- Resolved ambiguity between empty set and empty record values; empty records (with all fields set to `none`) are now represented as `{:}`.
- Added untyped parsing support, including the `UntypedValue` type and the `Node` AST representation.
- Added a "UI" test suite to ease test coverage expansion and migrated some integration tests to this new format.
- Replaced WasmValue::Error generic type with concrete WasmValueError.
- Removed completion support, which was more complex than it was worth

Fixes #18
Fixes #17
Fixes #6

### CODE REVIEW

File: src/lex.rs [hunk 1]
```diff
@@ -1,185 +1,121 @@
...
-    Whitespace,
+use std::fmt::Display;
+
+use logos::{Lexer, Logos, Span};
 
-    Dash,
+/// Represents a WAVE token.
+#[derive(Clone, Copy, Debug, PartialEq, Eq, Logos)]
+#[logos(error = LexingError)]
+#[logos(skip r"[ \t\r\n\f]+")]
```
Comment (sunfishcode) [inline src/lex.rs]: I don't have an opinion either way, but including "\f" here differs from the current [Wit definition of whitespace](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md#whitespace) and it'd be nice for those to agree.

File: tests/ui/accept-strings.wave [hunk 2]
```diff
@@ -0,0 +1,3 @@
+string("")
+string("WAVE🌊")
+string("\\\'\"\t\n\r")
```
Comment (sunfishcode) [inline tests/ui/accept-strings.wave]: This test doesn't currently include a string containing a Unicode escape.

File: tests/ui/ui.wit [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+
+    enum keyword-cases {
+        true,
+        false,
+        some,
+        none,
+        ok,
+        err,
+        inf,
+        nan,
```
Comment (sunfishcode) [inline tests/ui/ui.wit:56]: For completeness, it'd be good to have some non-keyword enum values here as well, so that the non-prefixed syntax can also be tested.

File: src/lex.rs [hunk 4]
```diff
@@ -1,185 +1,121 @@
...
+#[logos(subpattern label_word = r"[a-z][a-z0-9]*|[A-Z][A-Z0-9]*")]
```
Comment (sunfishcode) [inline src/lex.rs:14]: Why does the label_word pattern include upper-case letters? It's my understanding that Wit identifiers are only lower-case alphanumeric.

File: src/parser.rs [hunk 5]
```diff
@@ -1,726 +1,451 @@
...
     }
+}
 
-    fn parse_name(&mut self) -> Result<&str, ParserError> {
-        let span = self.expect(Token::Name)?;
-        let name = self.tokens.get_span(span);
-        Ok(name.strip_prefix('%').unwrap_or(name))
+pub(crate) fn flattenable(kind: WasmTypeKind) -> bool {
+    use WasmTypeKind::*;
+    !matches!(kind, Variant | Enum | Option | Result)
```
Comment (sunfishcode) [inline src/parser.rs]: With some/none/ok/err being keywords, is the plan still to make variant/enum flattenable? Or further, to make option-in-result or result-in-option flattenable? If so it'd be fine to do a TODO comment here for now.

**Review by sunfishcode — COMMENTED** [review]
Wow, so much here! Yay for logos, yay for the AST, yay for untyped values, yay for resolving ambiguities, and yay for the new test framework :smile: .

**Review by fibonacci1729 — APPROVED** [review]

File: src/lex.rs (hunk 1 above)
Comment (lann) [reply src/lex.rs]: Done.

File: tests/ui/accept-strings.wave (hunk 2 above)
Comment (lann) [reply tests/ui/accept-strings.wave]: Done.

File: tests/ui/ui.wit (hunk 3 above)
Comment (lann) [reply tests/ui/ui.wit:56]: Done.

File: src/lex.rs (hunk 4 above)
Comment (lann) [reply src/lex.rs:14]: Label words can be either all lowercase or all uppercase. I believe the idea is to allow retaining uppercase identifiers in bindings for languages that conventionally do that like Python.

https://github.com/WebAssembly/component-model/blob/main/design/mvp/Explainer.md
```ebnf
word          ::= [a-z] [0-9a-z]*
                | [A-Z] [0-9A-Z]*
```

File: src/parser.rs (hunk 5 above)
Comment (lann) [reply src/parser.rs]: Updated to allow inner variant/enum. I haven't thought through mixed option/result flattening yet so added a note as well.

**Comment by lann** [comment]
Other update highlights:

- Renamed repo to `wasm-wave` to match the crate
- Added `UntypedFuncCall` which holds AST for `<func-name>(<params...>)`
- Added trailing `;` to UI test cases
- Lots of doc updates
- Reorganized modules

File: src/lex.rs (hunk 4 above)
Comment (fibonacci1729) [reply src/lex.rs:14]: FWIW, this is what WAC implements now as well (added here https://github.com/peterhuene/wac/pull/29).

Comment (sunfishcode) [reply src/lex.rs:14]: Ah, I had forgotten about that. Looks good!
